---
- name: Test_git
  hosts: Client


  tasks:
     - name: Install git
       apt:
         name: git
         state: latest
         force_apt_get: yes
     - name: Install jar wrapper
       apt:
         name: jarwrapper
         state: latest
         force_apt_get: yes
     - git:
         repo: "https://github.com/Frolov-Viacheslav/HelloWorld.git"
         dest: /home/Slava/HelloWorld
     - name: Compiling java app
       shell: javac HelloWorld.java
       args:
         chdir: /home/Slava/HelloWorld/
     - lineinfile:
         path: /home/Slava/HelloWorld/MANIFEST.MF
         line: 'Main-class: HelloWorld'
         create: yes
     - name: Creating jar file
       shell: jar cvmf MANIFEST.MF Hello.jar HelloWorld.class
       args:
         chdir: /home/Slava/HelloWorld/
     - name: Change mod and move file
       copy:
         src: /home/Slava/HelloWorld/Hello.jar
         dest: /home/Slava/Hello.jar
         mode: +x
     - name: Run app
       shell: ./Hello.jar
       register: shell_result
       args:
         chdir: /home/Slava/ 
     - debug:
         var: shell_result.stdout_lines

     - name: Delete git directory (HelloWorld)
       file:
         path: /home/Slava/HelloWorld
         state: absent
         #recurse: yes

