#!groovy
properties([disableConcurrentBuilds()])

pipeline {
  agent{
    label 'master'
  }
 options {
    timestamps()
  }
  stages {
    stage('Send app') {
      steps {
        sh '''
            if  [ -d Calculator ]; then
            rm -r Calculator
            fi
            git clone "git@github.com:Frolov-Viacheslav/Calculator.git"
            ansible-playbook Calculator/Ansible/playbook.yml
            rm -r Calculator
            
           '''
      }
    }
  }
}
