---
- name: Build
  hosts: slave1

  tasks:
     - git:
         repo: "https://github.com/Frolov-Viacheslav/HelloWorld.git"
         dest: /home/jenkins/HelloWorld
         version: dev
     - name: Compiling java app
       shell: javac HelloWorld.java
       args:
         chdir: /home/jenkins/HelloWorld/
     - lineinfile:
           dest: /home/jenkins/HelloWorld/MANIFEST.MF
           line: 'Main-class: HelloWorld'
           create: yes
     - name: Creating jar file
       shell: jar cvmf MANIFEST.MF Hello.jar HelloWorld.class
       args:
         chdir: /home/jenkins/HelloWorld/
     - name: Move file and allow execute
       shell: mv /home/jenkins/HelloWorld/Hello.jar /home/jenkins/Hello.jar && chmod +x /home/jenkins/Hello.jar
     - name: Copy file to jenkins master
       shell: cp Hello.jar /var/jenkins_home
       args:
         chdir: /home/jenkins/
     - name: Run app
       shell: java -jar Hello.jar
       register: shell_result
       args:
         chdir: /home/jenkins/ 
     - debug:
         var: shell_result.stdout_lines
     - name: Delete git directory (HelloWorld)
       file:
         path: /home/jenkins/HelloWorld
         state: absent

