---
- name: Launch production
  hosts: docker
  tasks:
     - name: start docker container (production)
       shell: docker start productionci
     
- name: Deployment
  hosts: production
  tasks:
     - name: Copy jar file to production
       copy:
         src: /var/jenkins_home/Calculator-1.0-SNAPSHOT.jar
         dest: /home/jenkins
         
- name: Stop production
  hosts: docker
  tasks:     
     - name: stop docker container (production)
       shell: docker stop productionci


