---
- name: Build
  hosts: slave1

  tasks:
     - git:
         repo: "https://github.com/Frolov-Viacheslav/Calculator.git"
         dest: /home/jenkins/HelloWorld
         version: dev
     - name: Compiling java app
       shell: mvn package
       args:
         chdir: /home/jenkins/Calculator/
     #- lineinfile:
       #    dest: /home/jenkins/HelloWorld/MANIFEST.MF
        #   line: 'Main-class: HelloWorld'
        #   create: yes
     #- name: Creating jar file
     #  shell: jar cvmf MANIFEST.MF Hello.jar HelloWorld.class
    #   args:
       #  chdir: /home/jenkins/HelloWorld/
     - name: Move file and allow execute
       shell: mv /home/jenkins/Calculator/target/Calculator.jar /home/jenkins/Calculator.jar && chmod +x /home/jenkins/Calculator.jar
     - name: Copy file to jenkins master
       shell: cp Calculator.jar /var/jenkins_home
       args:
         chdir: /home/jenkins/
     #- name: Run app
      # shell: java -jar Calculator.jar
       #register: shell_result
       #rgs:
        # chdir: /home/jenkins/ 
     #- debug:
      #   var: shell_result.stdout_lines
     - name: Delete git directory (HelloWorld)
       file:
         path: /home/jenkins/Calculator
         state: absent

