---
- name: Build
  hosts: slave1

  tasks:
     - git:
         repo: "https://github.com/Frolov-Viacheslav/Calculator.git"
         dest: /home/jenkins/Calculator
         version: dev
     - name: Compiling java app
       shell: mvn package
       args:
         chdir: /home/jenkins/Calculator/
     - name: Move file and allow execute
       shell: mv /home/jenkins/Calculator/target/Calculator-1.0-SNAPSHOT.jar /home/jenkins/ && chmod +x /home/jenkins/Calculator-1.0-SNAPSHOT.jar
     - name: Copy file to jenkins master
       shell: cp Calculator-1.0-SNAPSHOT.jar /var/jenkins_home
       args:
         chdir: /home/jenkins/
     #- name: Delete git directory
       #file:
         #path: /home/jenkins/Calculator
         #state: absent

